### ISSUE TITLE
complexity of solution 1

### ISSUE THREAD

**Issue by lweitkamp** [sgraaf/Advent-of-Code-2020#1]
Hey Steven,

I think you can improve the complexity of the first solution somewhat;

```
def f(report):
    
    # O(n)
    x = {2020 - n: i for i, n in enumerate(report)}
    
    # O(n)
    for key, idx in x.items():
        if 2020 - key in x:
            return report[x[key]] * key
        
    return None
```

I'm not sure if you can extend this to the 3-solution case though.

**Comment by sgraaf** [comment]
Hi Laurens! Thank you for the feedback! 😃 I am well aware that there are solutions out there with a lower complexity (e.g. those that rely on hashing mechanisms)! My goal for this year's Advent of Code is first and foremost to complete every puzzle, and second to write good, clean Pythonic code. I don't necessarily care much for complexity (like quite a few others do).
